name: ci/cd

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: install SSH_KEY
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: build
        run: |
          make -C s21_cat
          make -C s21_grep

      - name: upload artifact s21_cat
        uses: actions/upload-artifact@v4
        with:
          name: s21_cat
          path: s21_cat/

      - name: upload artifact s21_grep
        uses: actions/upload-artifact@v4
        with:
          name: s21_grep
          path: s21_grep/
      
  unit_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: download artifact s21_cat
        uses: actions/download-artifact@v4
        with:
          name: s21_cat
          path: s21_cat/

      - name: download artifact s21_grep
        uses: actions/download-artifact@v4
        with:
          name: s21_grep
          path: s21_grep/

      - name: test
        run: |
          chmod +x s21_cat/test.sh
          chmod +x s21_grep/test.sh
          cd s21_cat && ./test.sh
          cd ../s21_grep && ./test.sh
  
  deploy:
    needs: unit_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install SSH_KEY
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: download artifact s21_cat
        uses: actions/download-artifact@v4
        with:
          name: s21_cat
          path: s21_cat
      
      - name: deploy-s21_cat
        run: |
          scp -o StrictHostKeyChecking=no \
            s21_cat/s21_cat \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/test-bot/s21_cat/

          scp -o StrictHostKeyChecking=no \
              s21_grep/s21_grep \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/test-bot/s21_grep/


